version: '3.8'

services:
  neo4j:
    image: neo4j:4.4  # You can use the latest stable version of Neo4j compatible with your app
    environment:
      - NEO4J_AUTH=neo4j/test  # Username: neo4j, Password: test
      - NEO4J_dbms_logs_debug_level=INFO
    ports:
      - "7687:7687"  # Bolt port
      - "7474:7474"  # HTTP Browser port
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
