name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run lint:check
    - run: npm run format:check
    - run: npm test
    - run: npm run build
    - run: npx typedoc

  # release:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'release'

